name: notification_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  android_intent_plus: ^5.0.2
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  permission_handler: ^11.3.1
  sound_mode: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tunes/yourmp3files.mp3
  #   - assets/notification_icon.png

  
